### ISSUE TITLE
Battery Monitor keeps showing notification for every decrease in battery percentage 

### ISSUE THREAD

**Issue by hotmailbelike** [maateen/battery-monitor#110]
Battery Monitor keeps showing notification for every decrease in battery percentage even though nothing has been changed in the config.toml file

![image](https://user-images.githubusercontent.com/25118296/84438950-2e797500-ac59-11ea-9d8e-cc0d94923f2b.png)

**Comment by maateen** [comment]
@hotmailbelike we have pushed a fix for this bug. Please install new codes and share your feedbacks.

**Comment by hotmailbelike** [comment]
I installed the new code. Did not work unfortunately, the bug still persists; I am still being notified on every decrease in battery percentage.

**Comment by maateen** [comment]
Sorry man! Please do me a favor.

Stop Battery Monitor service:

```shell
$ systemctl stop battery-monitor
```

Now, run battery-monitor command on terminal:

```shell
$ battery-monitor
```

You will see logs on the terminal. Please paste the logs generated from couple of events here.

**Comment by hotmailbelike** [comment]
I followed your instructions.
Here is a screenshot of my logs:
![image](https://user-images.githubusercontent.com/25118296/84497500-bbabe080-acd0-11ea-9f56-5e08403a9394.png)

**Comment by hotmailbelike** [comment]
I should let you know that I have changed a few things in the config.toml file.
But I am sure it's harmless but just in case here is a screenshot:

![image](https://user-images.githubusercontent.com/25118296/84497624-fc0b5e80-acd0-11ea-8482-994fe0fa2bbc.png)

**Comment by maateen** [comment]
Thanks for the information. I have tested battery-monitor on Ubuntu 20.04 on VirtualBox with Vagrant and couldn't reproduce the issue.

```shell
vagrant@focal:~$ battery-monitor
{"level":"info","msg":"Battery found.","time":"2020-06-12T12:14:47Z"}
{"level":"info","msg":"Monitoring the battery.","time":"2020-06-12T12:14:47Z"}
{"Charge":82,"Notification":"Discharging","SoundEnabled":false,"State":"Discharging","level":"info","msg":"","time":"2020-06-12T12:14:47Z"}
{"Charge":81,"Notification":"Third","SoundEnabled":false,"State":"Discharging","level":"info","msg":"","time":"2020-06-12T12:16:43Z"}
```

Perhaps, I have reformatted the monitoring logic part. Would you like to give it a try again with both default and your values?

[![Gitter](https://badges.gitter.im/battery-monitor/community.svg)](https://gitter.im/battery-monitor/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by hotmailbelike** [comment]
I tried again, no luck :(
